-- 1. Create catalogs table
CREATE TABLE public.catalogs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    user_id uuid NOT NULL,
    logo_url text,
    country_code text DEFAULT '+20',
    CONSTRAINT catalogs_pkey PRIMARY KEY (id),
    CONSTRAINT catalogs_name_key UNIQUE (name),
    CONSTRAINT catalogs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
ALTER TABLE public.catalogs ENABLE ROW LEVEL SECURITY;

-- 2. Create categories table
CREATE TABLE public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    parent_category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
    catalog_id bigint NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalogs (id) ON DELETE CASCADE
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 3. Create menu_items table
CREATE TABLE public.menu_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    description text,
    price numeric NOT NULL,
    image_url text,
    category_id bigint NOT NULL,
    catalog_id bigint NOT NULL,
    CONSTRAINT menu_items_pkey PRIMARY KEY (id),
    CONSTRAINT menu_items_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalogs (id) ON DELETE CASCADE,
    CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories (id) ON DELETE CASCADE
);
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;


-- 4. RLS Policies for catalogs
CREATE POLICY "Allow public read access to catalogs" ON public.catalogs FOR SELECT USING (true);
CREATE POLICY "Allow users to create their own catalog" ON public.catalogs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to update their own catalog" ON public.catalogs FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to delete their own catalog" ON public.catalogs FOR DELETE USING (auth.uid() = user_id);

-- 5. RLS Policies for categories
CREATE POLICY "Allow public read access to categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow owners to manage their categories" ON public.categories FOR ALL
USING (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs
    WHERE id = categories.catalog_id
  )
)
WITH CHECK (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs
    WHERE id = categories.catalog_id
  )
);

-- 6. RLS Policies for menu_items
CREATE POLICY "Allow public read access to menu items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Allow owners to manage their menu items" ON public.menu_items FOR ALL
USING (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs
    WHERE id = menu_items.catalog_id
  )
)
WITH CHECK (
  ( SELECT auth.uid() = user_id
    FROM public.catalogs
    WHERE id = menu_items.catalog_id
  )
);

-- 7. Create Storage Buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('logos', 'logos', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('menu_images', 'menu_images', true);

-- 8. Storage Policies for logos
CREATE POLICY "Allow public read access on logos" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'logos');
CREATE POLICY "Allow authenticated users to upload logos" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'logos');
CREATE POLICY "Allow owners to update their logos" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'logos' AND owner = auth.uid());
CREATE POLICY "Allow owners to delete their logos" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'logos' AND owner = auth.uid());

-- 9. Storage Policies for menu_images
CREATE POLICY "Allow public read access on menu images" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'menu_images');
CREATE POLICY "Allow authenticated users to upload menu images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'menu_images');
CREATE POLICY "Allow owners to update their menu images" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'menu_images' AND owner = auth.uid());
CREATE POLICY "Allow owners to delete their menu images" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'menu_images' AND owner = auth.uid());
