-- Drop existing tables if they exist
DROP TABLE IF EXISTS "menu_items";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "catalogs";

-- Create catalogs table
CREATE TABLE public.catalogs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    name text NOT NULL,
    logo_url text NULL,
    cover_url text NULL,
    enable_subcategories boolean NOT NULL DEFAULT false,
    CONSTRAINT catalogs_pkey PRIMARY KEY (id),
    CONSTRAINT catalogs_name_key UNIQUE (name),
    CONSTRAINT catalogs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT catalogs_user_id_key UNIQUE (user_id)
);
ALTER TABLE public.catalogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access." ON public.catalogs FOR SELECT USING (true);
CREATE POLICY "Allow individual insert access" ON public.catalogs FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Allow individual update access" ON public.catalogs FOR UPDATE USING ((auth.uid() = user_id));

-- Create categories table
CREATE TABLE public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    catalog_id bigint NOT NULL,
    parent_category_id bigint NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalogs (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT categories_parent_category_id_fkey FOREIGN KEY (parent_category_id) REFERENCES public.categories (id) ON DELETE CASCADE
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access." ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow insert access to catalog owners" ON public.categories FOR INSERT WITH CHECK (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);
CREATE POLICY "Allow update access to catalog owners" ON public.categories FOR UPDATE USING (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);
CREATE POLICY "Allow delete access to catalog owners" ON public.categories FOR DELETE USING (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);

-- Create menu_items table
CREATE TABLE public.menu_items (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    description text NULL,
    price real NOT NULL,
    image_url text NULL,
    category_id bigint NOT NULL,
    catalog_id bigint NOT NULL,
    CONSTRAINT menu_items_pkey PRIMARY KEY (id),
    CONSTRAINT menu_items_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalogs (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories (id) ON UPDATE CASCADE ON DELETE CASCADE
);
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access." ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Allow insert access to catalog owners" ON public.menu_items FOR INSERT WITH CHECK (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);
CREATE POLICY "Allow update access to catalog owners" ON public.menu_items FOR UPDATE USING (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);
CREATE POLICY "Allow delete access to catalog owners" ON public.menu_items FOR DELETE USING (
    (auth.uid() = ( SELECT user_id FROM catalogs WHERE id = catalog_id ))
);

-- Create Supabase Storage buckets
insert into storage.buckets (id, name, public)
values ('logos', 'logos', true);

insert into storage.buckets (id, name, public)
values ('menu_images', 'menu_images', true);

CREATE POLICY "Allow public read access to logos" ON storage.objects FOR SELECT TO anon, authenticated USING ( bucket_id = 'logos' );
CREATE POLICY "Allow authenticated users to upload logos" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'logos' );
CREATE POLICY "Allow owners to update logos" ON storage.objects FOR UPDATE TO authenticated USING ( auth.uid() = owner );

CREATE POLICY "Allow public read access to menu images" ON storage.objects FOR SELECT TO anon, authenticated USING ( bucket_id = 'menu_images' );
CREATE POLICY "Allow authenticated users to upload menu images" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'menu_images' );
CREATE POLICY "Allow owners to update menu images" ON storage.objects FOR UPDATE TO authenticated USING ( auth.uid() = owner );
