-- Create catalogs table
CREATE TABLE catalogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  logo_url TEXT,
  cover_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id BIGINT REFERENCES catalogs(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  parent_category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create menu_items table
CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id BIGINT REFERENCES catalogs(id) ON DELETE CASCADE NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create storage buckets for logos and item images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('logos', 'logos', TRUE, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml']),
  ('menu_images', 'menu_images', TRUE, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp']);

-- Enable Row Level Security (RLS)
ALTER TABLE catalogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

-- Policies for catalogs table
CREATE POLICY "Users can manage their own catalog." ON catalogs
  FOR ALL
  USING (auth.uid() = user_id);
CREATE POLICY "Catalogs are public to read." ON catalogs
  FOR SELECT
  USING (TRUE);

-- Policies for categories table
CREATE POLICY "Users can manage their own categories." ON categories
  FOR ALL
  USING (EXISTS (
    SELECT 1 FROM catalogs WHERE catalogs.id = categories.catalog_id AND catalogs.user_id = auth.uid()
  ));
CREATE POLICY "Categories are public to read." ON categories
  FOR SELECT
  USING (TRUE);

-- Policies for menu_items table
CREATE POLICY "Users can manage their own menu items." ON menu_items
  FOR ALL
  USING (EXISTS (
    SELECT 1 FROM catalogs WHERE catalogs.id = menu_items.catalog_id AND catalogs.user_id = auth.uid()
  ));
CREATE POLICY "Menu items are public to read." ON menu_items
  FOR SELECT
  USING (TRUE);

-- Policies for storage buckets
CREATE POLICY "Logo images are publicly accessible." ON storage.objects
  FOR SELECT
  USING (bucket_id = 'logos');
CREATE POLICY "Users can manage their own logo." ON storage.objects
  FOR INSERT, UPDATE, DELETE
  USING (
    bucket_id = 'logos' AND
    auth.uid() = (
      SELECT user_id FROM catalogs WHERE catalogs.logo_url LIKE '%' || storage.objects.name
    )
  );

CREATE POLICY "Menu item images are publicly accessible." ON storage.objects
  FOR SELECT
  USING (bucket_id = 'menu_images');
CREATE POLICY "Users can manage their own menu item images." ON storage.objects
  FOR INSERT, UPDATE, DELETE
  USING (
    bucket_id = 'menu_images' AND
    auth.uid() = (
      SELECT c.user_id FROM catalogs c JOIN menu_items mi ON c.id = mi.catalog_id WHERE mi.image_url LIKE '%' || storage.objects.name
    )
  );
