create table public.item_variants (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  menu_item_id bigint not null references public.menu_items (id) on delete cascade,
  name text not null,
  price numeric not null,
  constraint item_variants_pkey primary key (id)
);

alter table public.item_variants enable row level security;

-- RLS Policies for item_variants

-- 1. Public read access
create policy "Allow public read access to item_variants"
  on public.item_variants for select
  using (true);

-- 2. Owners management access (using catalog owner check via menu_items -> catalogs)
create policy "Allow owners to manage their item variants"
  on public.item_variants for all
  using (
    exists (
      select 1 from public.menu_items m
      join public.catalogs c on m.catalog_id = c.id
      where m.id = item_variants.menu_item_id
      and c.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.menu_items m
      join public.catalogs c on m.catalog_id = c.id
      where m.id = item_variants.menu_item_id
      and c.user_id = auth.uid()
    )
  );
